version: '3'

services:
  postgres:
    image: "postgres" # use latest official postgres version
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=twitter
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  web:
    image: "angular-twitter"
    environment:
      - DatabaseURL=postgres
    env_file:
      - .env
    ports:
      - 8080:8080


volumes:
  database-data: # named volumes can be managed easier using docker-compose